# website settings
website:
  title: "Adams Ceballos-Concha"                               
  description: "Adams is an applied marine & aquaculture economist."
  image: img/my_image1.jpg
  favicon: img/favicon.png
  site-url: "https://www.adamsceballos.com"
  repo-url: "https://github.com/adamsconchallos/adamsconchallos"
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Research"
        href: research/index.qmd
      - text: "Blog"
        file: blog/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/adamsconchallos
      - icon: linkedin
        href: https://www.linkedin.com/in/adams-ceballos-concha-0403633a/
      - icon: envelope
        aria-label: email
        href: "mailto:aceballos@ufl.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Adams Ceballos-Concha</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    
# Metadata stuff
pagetitle: "{{< meta title >}} | Adams Ceballos-Concha"
author-meta: "Adams Ceballos"

render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
resources:
  - CNAME
